// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Api.Modules.KSeF.Database;

#nullable disable

namespace Platform.Module.Ksef.Migrations.Ksef
{
    [DbContext(typeof(KsefDbContext))]
    partial class KsefDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefAutoSyncSettings", b =>
                {
                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ContextNip")
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Environment", "ContextNip");

                    b.ToTable("ksef_auto_sync_settings", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefPurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerIdentifierType")
                        .HasColumnType("text")
                        .HasColumnName("buyer_identifier_type");

                    b.Property<string>("BuyerIdentifierValue")
                        .HasColumnType("text")
                        .HasColumnName("buyer_identifier_value");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text")
                        .HasColumnName("buyer_name");

                    b.Property<string>("ContextNip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_attachment");

                    b.Property<string>("InvoiceHash")
                        .HasColumnType("text")
                        .HasColumnName("invoice_hash");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("KsefNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ksef_number");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<DateOnly?>("PermanentStorageDate")
                        .HasColumnType("date")
                        .HasColumnName("permanent_storage_date");

                    b.Property<string>("SellerName")
                        .HasColumnType("text")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerNip")
                        .HasColumnType("text")
                        .HasColumnName("seller_nip");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal?>("VatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_amount");

                    b.HasKey("Id");

                    b.HasIndex("KsefNumber")
                        .HasDatabaseName("ix_ksef_purchase_invoices_ksef_number");

                    b.HasIndex("Environment", "ContextNip")
                        .HasDatabaseName("ix_ksef_purchase_invoices_env_ctx");

                    b.ToTable("ksef_purchase_invoices", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefRateLimitState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset?>("BlockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until_utc");

                    b.Property<DateTimeOffset?>("Last429AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_429_at_utc");

                    b.Property<string>("LastDetails")
                        .HasColumnType("text")
                        .HasColumnName("last_details");

                    b.Property<int?>("RetryAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_after_seconds");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId", "Environment");

                    b.ToTable("ksef_rate_limit_state", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefSyncLock", b =>
                {
                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ContextNip")
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<Guid>("LockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("locked_by_user_id");

                    b.Property<DateTimeOffset>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.HasKey("Environment", "ContextNip");

                    b.ToTable("ksef_sync_lock", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefSyncState", b =>
                {
                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ContextNip")
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastPermanentStorageHwmDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_permanent_storage_hwm_date");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Environment", "ContextNip");

                    b.ToTable("ksef_sync_state", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefUserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active_type");

                    b.Property<byte[]>("CertCrt")
                        .HasColumnType("bytea")
                        .HasColumnName("cert_crt");

                    b.Property<string>("CertFingerprintSha256")
                        .HasColumnType("text")
                        .HasColumnName("cert_fingerprint_sha256");

                    b.Property<byte[]>("CertKey")
                        .HasColumnType("bytea")
                        .HasColumnName("cert_key");

                    b.Property<byte[]>("CertKeyPasswordEnc")
                        .HasColumnType("bytea")
                        .HasColumnName("cert_key_password_enc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_valid_to");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("TokenValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_valid_to");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Environment")
                        .HasDatabaseName("ix_ksef_user_credentials_user_env");

                    b.ToTable("ksef_user_credentials", "app_core");
                });
#pragma warning restore 612, 618
        }
    }
}
