// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Api.Infrastructure.Database;

#nullable disable

namespace Platform.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223090000_LowercaseRbacColumns")]
    partial class LowercaseRbacColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app_core")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                                                .HasColumnName("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                                                .HasColumnName("code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                                                .HasColumnName("description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                                                .HasColumnName("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                                                .HasColumnName("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                                                .HasColumnName("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                                                .HasColumnName("permission_id")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                                                .HasColumnName("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdUpn")
                                                .HasColumnName("ad_upn")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                                                .HasColumnName("created_at_utc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalUserId")
                                                .HasColumnName("external_user_id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                                                .HasColumnName("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                                                .HasColumnName("login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                                                .HasColumnName("password_hash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                                                .HasColumnName("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                                                .HasColumnName("role_id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("user_roles", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.RolePermission", b =>
                {
                    b.HasOne("Platform.Api.Core.RBAC.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Api.Core.RBAC.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Platform.Api.Core.RBAC.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
