// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Api.Infrastructure.Database;

#nullable disable

namespace Platform.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304030125_AddInstanceIdToUserSessions")]
    partial class AddInstanceIdToUserSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app_core")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefAutoSyncSettings", b =>
                {
                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ContextNip")
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Environment", "ContextNip");

                    b.ToTable("ksef_auto_sync_settings", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefPurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerIdentifierType")
                        .HasColumnType("text")
                        .HasColumnName("buyer_identifier_type");

                    b.Property<string>("BuyerIdentifierValue")
                        .HasColumnType("text")
                        .HasColumnName("buyer_identifier_value");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text")
                        .HasColumnName("buyer_name");

                    b.Property<string>("ContextNip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_amount");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_attachment");

                    b.Property<string>("InvoiceHash")
                        .HasColumnType("text")
                        .HasColumnName("invoice_hash");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("KsefNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ksef_number");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_amount");

                    b.Property<DateOnly?>("PermanentStorageDate")
                        .HasColumnType("date")
                        .HasColumnName("permanent_storage_date");

                    b.Property<string>("SellerName")
                        .HasColumnType("text")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerNip")
                        .HasColumnType("text")
                        .HasColumnName("seller_nip");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal?>("VatAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_amount");

                    b.HasKey("Id");

                    b.HasIndex("KsefNumber")
                        .HasDatabaseName("ix_ksef_purchase_invoices_ksef_number");

                    b.HasIndex("Environment", "ContextNip")
                        .HasDatabaseName("ix_ksef_purchase_invoices_env_ctx");

                    b.ToTable("ksef_purchase_invoices", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefRateLimitState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset?>("BlockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until_utc");

                    b.Property<DateTimeOffset?>("Last429AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_429_at_utc");

                    b.Property<string>("LastDetails")
                        .HasColumnType("text")
                        .HasColumnName("last_details");

                    b.Property<int?>("RetryAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_after_seconds");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId", "Environment");

                    b.ToTable("ksef_rate_limit_state", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefSyncLock", b =>
                {
                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ContextNip")
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<Guid>("LockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("locked_by_user_id");

                    b.Property<DateTimeOffset>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.HasKey("Environment", "ContextNip");

                    b.ToTable("ksef_sync_lock", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefSyncState", b =>
                {
                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ContextNip")
                        .HasColumnType("text")
                        .HasColumnName("context_nip");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastPermanentStorageHwmDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_permanent_storage_hwm_date");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Environment", "ContextNip");

                    b.ToTable("ksef_sync_state", "app_core");
                });

            modelBuilder.Entity("Platform.Api.Modules.KSeF.Entities.KsefUserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active_type");

                    b.Property<byte[]>("CertCrt")
                        .HasColumnType("bytea")
                        .HasColumnName("cert_crt");

                    b.Property<string>("CertFingerprintSha256")
                        .HasColumnType("text")
                        .HasColumnName("cert_fingerprint_sha256");

                    b.Property<byte[]>("CertKey")
                        .HasColumnType("bytea")
                        .HasColumnName("cert_key");

                    b.Property<byte[]>("CertKeyPasswordEnc")
                        .HasColumnType("bytea")
                        .HasColumnName("cert_key_password_enc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_valid_to");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("TokenValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_valid_to");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Environment")
                        .HasDatabaseName("ix_ksef_user_credentials_user_env");

                    b.ToTable("ksef_user_credentials", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.Config.Entities.CompanyInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nip");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name");

                    b.HasKey("Id");

                    b.ToTable("company_info", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.Config.Entities.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_configs", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.Config.Entities.SystemLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at_utc");

                    b.Property<string>("LicenseBlob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_blob");

                    b.HasKey("Id");

                    b.ToTable("system_license", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text")
                        .HasColumnName("module_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdUpn")
                        .HasColumnType("text")
                        .HasColumnName("ad_upn");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text")
                        .HasColumnName("external_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("instance_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at_utc");

                    b.Property<DateTime?>("LogoutAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logout_at_utc");

                    b.Property<string>("LogoutReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logout_reason");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("machine_name");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions", "app_core");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.RolePermission", b =>
                {
                    b.HasOne("Platform.Kernel.Core.RBAC.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Kernel.Core.RBAC.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.UserRole", b =>
                {
                    b.HasOne("Platform.Kernel.Core.RBAC.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Kernel.Core.RBAC.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.UserSession", b =>
                {
                    b.HasOne("Platform.Kernel.Core.RBAC.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Platform.Kernel.Core.RBAC.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
